### ISSUE TITLE
TB102.4.2 Printing Tools not printing attachment names in header also ...

### ISSUE THREAD

**Issue by WilllowsMagic** [cleidigh/printing-tools-ng#148]
TB102.4.2 Printing Tools not printing attachment names in header.
Header order set to Subject, Attachment, From, To, Date (CC and BCC hidden)
Header order prints as Subject, From, Date, To, CC.
So Printing Tools is not controlling the Header order.
We need the attachment names in the header, so we don't have to print out the entire email!
Any ideas?

**Comment by cleidigh** [comment]
@WilllowsMagic 
I did a sanity check on my windows 10 dev machine under TB102.4.2, PTNG using my example test email with your headers order. This printed as expected. See file.
[PrintingTools NG example formatting.pdf](https://github.com/cleidigh/printing-tools-ng/files/10015665/PrintingTools.NG.example.formatting.pdf)

First can you id the os and ptng versions.
Second can you add a border and verify that is printed. I am wondering if ptng is not being invoked.
@cleidigh

**Comment by kiki-ja** [comment]
@WilllowsMagic 

>Header order prints as Subject, From, Date, To, CC.
>So Printing Tools is not controlling the Header order.

It appears that Thunderbird is still in the default order when printing.
In other words, PrintingTools NG is not enabled.

The reason is that Thunderbird's default order is Subject, From, Date, To, CC, BCC, and it prints the attachment name and size at the bottom of the message body.
This order cannot be changed.
Please see the screenshot.

　![Normal print preview -01](https://user-images.githubusercontent.com/80428201/202903879-d853c121-7168-4657-8196-00a5bc7f524f.png)

>We need the attachment names in the header, so we don't have to print out the entire email!

It is possible that there is a conflict with another add-on.
Please refer to the following for how to deal with the problem.
Also, we urge you to find out which add-ons seem to be conflicting with each other.

Reference:
https://github.com/cleidigh/printing-tools-ng/issues/149#issuecomment-1321104420

@kiki-ja
