### ISSUE TITLE
Printing Tools is incompatible with Thunderbird 78.2.2

### ISSUE THREAD

**Issue by GeepsJay** [cleidigh/printing-tools-ng#15]
Hi Christopher, Thunderbird has updated to 78.2.2 and I find that Printing Tools NG has been disabled. Thought I'd let you know.

**Comment by Mobeeuz** [comment]
Yes, I got magically moved to 78.xx and can't move back now without losing mail. I swear the only reason they update Thunderbird is to break all the plugins. PT's additions are an obvious staple, and should be folded into the actual codebase.

**Comment by cleidigh** [comment]
@Mobeeuz 
@GeepsJay 
I need to finish up  localfolders and another maintenance Release
then I will do the printing conversion, I think now we should go quickly

@cleidigh

**Comment by Mobeeuz** [comment]
Excellent news, thanks for all your hard work! 👍

**Comment by GeepsJay** [comment]
Thank you so much for your work - appreciate it

**Comment by archfiddler** [comment]
Hi Christopher,
Great tool (essential - how do others work without it?) Any news on beta release?

**Comment by cleidigh** [comment]
@archfiddler 
thanks for the post/comments!
as I mentioned above this is next on my list, only problem is things keep popping
up in front of it ;-)
I hope I might have a window this weekend.  if it's a straightforward conversion
I will be able to release quickly, unfortunately with the three other extensions
import export tools ng, local folder and Columns wizard I have converted each had
gotchas that took a lot of extra time.  PT should be easier, but it has a couple of unique things
that I am hoping I'm are nonissues 
regardless sooner rather than later I will get it going!
Christopher

**Comment by cleidigh** [comment]
@GeepsJay 
@Mobeeuz 
@archfiddler 
I have the first beta:

https://github.com/cleidigh/printing-tools-ng/issues/18

**Comment by librelegal** [comment]
Thank you Christopher for your work, I very much depend on this addon, so I am very happy. With 78.6.0, 64bit, Linux I cannot install the beta. I would do it as soon as possible and comment on the outcome

**Comment by Mobeeuz** [comment]
I get the same results as librelegal in Windows 10...

**Comment by cleidigh** [comment]
@Mobeeuz 
Santa had a bad link (thanks @librelegal )
check out the corrected link in #18 
happy holidays
Christopher
