### ISSUE TITLE
Printing calendars does not work when print-tools-ng is enabled

### ISSUE THREAD

**Issue by SeventhUnderhand** [cleidigh/printing-tools-ng#176]
I open the calendar tab and try to Ctrl+P like I normally would but no print dialog pops up nor does it print. 

If I disable the extension it works as expected. 

Is there a way to disable the extension just on the Calendar tab?

**Comment by cleidigh** [comment]
@SeventhUnderhand 
Thanks for the post.
Good timing! I am days away from a major new release so I will make sure this is addressed. I think I reproduced it already, however, if you could indicate your os, tb and ptng versions that would be great.
@cleidigh

**Comment by SeventhUnderhand** [comment]
Windows 11 Pro Build 22621 & Windows 10 Pro Build 19044 
TB  102.8.0
ptng 2.1.5

**Comment by cleidigh** [comment]
@SeventhUnderhand 
Thanks. Just found the Calendar does not report a URL like all other tabs, that tripped me up...
I should be able to post a new beta in a day or two.
I will post a link here.
@cleidigh

**Comment by SeventhUnderhand** [comment]
> @SeventhUnderhand 
> Thanks. Just found the Calendar does not report a URL like all other tabs, that tripped me up...
> I should be able to post a new beta in a day or two.
> I will post a link here.
> @cleidigh 

Sounds good, thanks!

**Comment by cleidigh** [comment]
@SeventhUnderhand 
You can grab the b32pre2 beta that addresses this and the related Conversations issue. The link is at the top of: 
- #157 

If you get an error installing, check out : 
- #154 
@cleidigh

**Comment by SeventhUnderhand** [comment]
@cleidigh thanks, ill download it and test it out

**Comment by RRoenn** [comment]
> Test report.
> I was able to print the calendar appointments.

I can confirm

@RRoenn

**Comment by cleidigh** [comment]
@kiki-ja 
@RRoenn 
Thanks for the confirmation.
I have a couple small things I have to do and testing on Linux and I think we are set.

Something funny: 
Remember the issue with the icon missing because the CSS was not loading? I told you I found the file was not loading as its extension was.Js and should be.js
My eye gaze automatically capitalizes letters after a period so I have to correct these. So you remember I fixed that and the icon restored.
Well I was testing last night and the icon is gone!
I look at the filename and go figure, the name is wrong again???
So i think we have some Github gremlins or ghosts %-) !!
@cleidigh

**Comment by cleidigh** [comment]
@SeventhUnderhand 
Any testing?
@cleidigh

**Comment by SeventhUnderhand** [comment]
@cleidigh yes, sorry. Works on all 3 machines that I have tested it on.

**Comment by cleidigh** [comment]
@SeventhUnderhand 
Great, will close.
Watch 
- #157 
Hoping to put into review Q tomorrow!
@cleidigh
