### ISSUE TITLE
[Linux] page setup not easily accessible

### ISSUE THREAD

**Issue by librelegal** [cleidigh/printing-tools-ng#2]
In Version 0.1.2. I cannot set the page margins / header lines before chosing with printer to use. After chosing a printer I can set the letter size for all printers and for the exact printer, these settings seems to be set once and they stay even after a new start of thunderbird.

This is different under Windows10 where I can access the page settings and thus the page margins and header lines before chosing a special printer.

**Comment by cleidigh** [comment]
@librelegal 
There are several peculiarities with Thunderbird in printing.  Unfortunately I just starting to learn some of these having just taken over and released NG.  I only have L Mint  in a virtual machine and given I am disabled it is difficult to do anything with an actual printer.
I am currently working on the next small version update. Besides multiple new locales, I have also added a new option to set the default printer.  On Windows the printer is not necessarily saved from use to use.  Now if you set the printer under the global printing options it will be persistent.
This is particularly useful for the non- dialogue mode.
This might also help with the printing options (page size et cetera)  I honestly do not know.
you can try the beta here:
https://github.com/cleidigh/printing-tools-ng/blob/default-printer-test/xpi/printing-tools-ng-0.1.3-dpt3-tb.xpi
otherwise I will probably need some help diagnosing/testing on Linux
@cleidigh

**Comment by librelegal** [comment]
Thank your for answering that quickly. I tested 0.1.3 in debian 10, I see no change in the behaviour, but as I only had to set thing once and since it does work it should be just fine. In Windows 10 I did not have the problem described in issue #1.  
Thank you again for working on printing tools

**Comment by cleidigh** [comment]
@librelegal 
sounds good
closing
