### ISSUE TITLE
Duplicate accesskey (o)

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#204]
@cleidigh

PTNG 2.2.1, 2.2.2-b6, 3.0-b1
Thunderbird 102.10.0 64bit
Windows 10 Pro 22H2 64bit

The PTNG Options accesskey under "Menu" -> "File" is a duplicate of the "Open" accesskey.
Is it possible to change this?

![file-menu-o](https://user-images.githubusercontent.com/80428201/232224176-27c67f10-0eb5-441e-8b86-2374f3424d3d.png)

@kiki-ja

**Comment by cleidigh** [comment]
I guess I could use N in NG?
How does that sound?
Christopher

**Comment by kiki-ja** [comment]
@cleidigh

"N" is duplicated since it is used in the "**N**ew" access key.

![file-menu-n-en-US](https://user-images.githubusercontent.com/80428201/232234751-c7e3e755-2fb8-46f9-acb3-553c0772f712.png)

![file-menu-n-ja](https://user-images.githubusercontent.com/80428201/232234763-f2ada1cf-9a94-4fcf-b9ca-c0af5a71ffe4.png)

If you choose an access key other than those listed below, you should be fine.
n, o, c, a, z, s, w, d, b, e, r, f, y, l, p, x

@kiki-ja

**Comment by cleidigh** [comment]
Done, changed to 'G'

**Comment by RRoenn** [comment]
@cleidigh 
Hello :-)
I don't use these keys, are you sure these access keys only apply to the current menu?
G is Go To like search for

How those it work? With STRG or ALT? Or open menu then access key?

Greetings
@RRoenn

**Comment by cleidigh** [comment]
@RRoenn 
This shortcut is only for the File menu and only available there independent of everything else.
@cleidigh

**Comment by DenB10** [comment]
Hi,

I don't think the duplication of an accesskey is important, since you only need to press the "Enter" key when the desired entry is highlighted.
For example, in the "File" menu, if you press the o key, the "Open" entry is first highlighted and then if you press o again, the "PrintingTools NG Options" entry becomes highlighted. Press the "Enter" key to open the PTNG options page.

Moreover, it may be that the choice of a letter as accesskey is unique in one language but not in another!

That's why it's useless to take the trouble with this. It's just my humble opinion.

**Comment by kiki-ja** [comment]
@cleidigh

PTNG 2.2.2-b7
Thunderbird 102.10.0 64bit
Windows 10 Pro 22H2 64bit

>Done, changed to 'G'

Duplicate access keys have been eliminated and one-step access is now possible.
It is comfortable.
Thank you very much.

@kiki-ja

**Comment by kiki-ja** [comment]
Done, fixed.

**Comment by cleidigh** [comment]
@DenB10 
I agree in general with what you commented. The change here is using G in (NG) which is locale independent. Thunderbird does in most cases use locale specific shortcuts.
I use Thunderbird locale specific translations for print and print preview, not that they are perfect...

**Comment by DenB10** [comment]
@cleidigh 
G may be local independent but not sure if it is not duplicate in a certain language, which would go against what kiki-ja wants!
But whatever, if everyone is happy with G, I am too :+1:

**Comment by cleidigh** [comment]
@DenB10 
That's a good point... I can do a quick check on the other locales.
@cleidigh

**Comment by DenB10** [comment]
@cleidigh 
No thanks, no need to waste your time on such a check.
For the reason I mentioned above, the same accesskey can be assigned to two different commands in the same menu without it being very annoying: three keys to press instead of one is not death, especially since I'm not sure that many people use accesskeys!

**Comment by cleidigh** [comment]
@DenB10 
I think you are right, using the dropdown on the button is probably what most people use.
@cleidigh
