### ISSUE TITLE
Header font not changeable

### ISSUE THREAD

**Issue by pstein** [cleidigh/printing-tools-ng#209]
I wanted to change the current header font to something smaller

So I went (on Win10 v22H2, 64bit Portable TB v102.10.2 and Printing Tools NG v2.21.1 onto the Tab 

Printing Tool Options---->Headers 

and changed the value 

Use fonts with a size in pixel of: "Georgia" with size "7"

But (after TB restart) the printed message header font remains as big a before.
No matter what I select for "Use fonts with a size in pixel of" the current font is kept.

Changes of other header settings seems to be problematic too.
If I select another header background color: Background remains white

Whats wrong?

Maybe its a side effect of my additional font definitions in my customized "userChrome .css".

**Comment by cleidigh** [comment]
@pstein 
Thanks for the post.
I just did a sanity check with the latest TB102 and PTNG v2.2.1 changing the header font to Consolas with a couple different sizes. That all went as expected. I don't use userChrome.css so I can't say anything useful on that other than you might be correct to eliminate it to test.
The fonts are done with inline styleing so that takes precedence over css so bit skeptical.
If you set the debug options to two words separated by a space you can see the initial message and the final output which will show the fonts. Use : 
initialsource finaloutput 
in debug options and print then look at the console output.

The Print Backgrounds option in the preview has to be used to enable any background colors. My next maintenance release actually does this automatically, have beta if interested.
So you can post your output here and we can figure it out.
@cleidigh

**Comment by pstein** [comment]
Hello Christopher,
thank you for your comments.

First of all:
userChrome.css, userChrome.js and userContent.css
seem not to play a role. I moved them all out of my installation and your PTNG does work either.

So as a next step I enter yuzr suggested debug options
initialsource finaloutput
and had a view at the console output.

Much to my surprise the PTNG final output shows the correct font specs. and background color. Console starts with:

```
<html><head>
<title>test title</title>
<link rel="important stylesheet" href="chrome://messagebody/skin/messageBody.css">
</head>
<body><table class="moz-header-part1 moz-main-header orig" style="font-family: Courier New; font-size: 7px; table-layout: fixed; margin-right: 10px; 
border: 1.4px solid black; background-color: rgb(255, 0, 128);" width="100%" cellspacing="0" cellpadding="0" border="0">
<tbody><tr><td style="vertical-align: top; padding: 3px 0px 0px 5px;" width="110px">.......
```

But in the final PDF always the same big, fat font appears

So I am helpless

Maybe some messages appearing after the PTNG final output give some hint:

Element.releaseCapture() is deprecated. Use Element.releasePointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/releasePointerCapture menupopup.js:169:13
Message pane focused  printingtoolsng-pengine.js:176:14
TypeError: browser is null

**Comment by pstein** [comment]
I have got it (partially):

The solution consists of 3 parts:

1.) First of all in Thunderbird Settings it must be allowed that message could can their font and the minimum font size.
Have a look at the attached snapshot
Here I denied (in the past) to change the font and set a minimum size of 14

2.) Printing Tools NG WebExtension confused the user that it CAN change the header font although cannot.
PTNG should check whether a font and font size change is possible at all.
If it it not (like here) then the header font change drop down should be disabled/greyed out and "set by Thunderbird" or similar should be shown.

3.) Then at last my userChrome.css or UserContent.css comes into play.
After PTNG changed the font userChrome.css or userContent.css modifies (again) the current header font 
So it has the highest priority.

I have to investigate which of the multiple CSS statements refers to the message header font.
Do you have an idea?
I am not an userChrome.css expert.

![Allow messages to use other font](https://user-images.githubusercontent.com/2775875/234310159-30d228ac-b35c-4fa5-ab03-731de0efaf70.png)
