### ISSUE TITLE
Header text fonts can't changed?

### ISSUE THREAD

**Issue by kiki-ja** [cleidigh/printing-tools-ng#210]
@cleidigh

PTNG 2.2.2-b8, 2.2.2
Thunderbird 102.10.0 64bit
Windows 10 Pro 22H2 64bit 

Mentioned #209

In previous versions, it was possible to change it.
Now header text fonts can no longer be changed.
It can be reproduced on any printer.

Font size changes are possible and fine.

Am I the only one experiencing this problem?

------   My case  ------    
Font settings on Thunderbird:
BIZ UDP Gothic, UTF-8
Font setting on PTNG options:
extensions.printingtoolsng.headers.font_family = Impact
Printer:
Save to PDF
The messages tested were written in UTF-8.
All extensions.printingtoolsng.* have been cleaned up removed from prefs.js.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
Can you clarify?
Are you having this problem?
I have no problem so this would be very odd.
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

>Can you clarify?

Screenshots and sample messages are available.

>Are you having this problem?

It is not a big problem.

>I have no problem so this would be very odd.

Reproduction conditions are unknown.
I will test and explore.

**[Screenshots]**
![PTNG-Header-Font-Impact](https://user-images.githubusercontent.com/80428201/233540614-4ea2879c-8610-41e1-9e3f-fd1e264e0060.png)

![Sample-message-impact-font2](https://user-images.githubusercontent.com/80428201/233540637-96c7e0fd-6788-4e65-a4ca-8ec2d89a4b7f.png)

![TB-Font- BIZ_UDP_Gothic](https://user-images.githubusercontent.com/80428201/233540658-a20f515b-0c37-4428-8fee-23e81a46fe4e.png)

**[Sample message]**
[Sample_message.zip](https://github.com/cleidigh/printing-tools-ng/files/11292196/Sample_message.zip)

@kiki-ja

**Comment by kiki-ja** [comment]
@cleidigh

I found the cause of the problem.
It was because the font was specified in userContent.css as follows.
After removing this, the problem was resolved.

**|* * {
font-family: 'BIZ UDPGothic'; 
}

![Headers-Impact-Font2](https://user-images.githubusercontent.com/80428201/233748662-ee83ddad-8bc1-4038-906b-e5f3a28039e7.png)

I am very sorry for the trouble.

@pstein
Please refer to my problem-solving example.
If you have specified font-family and font-size in userChrome.css or userContent.css, I recommend that you try temporarily deleting them to see if that solves the problem.

@kiki-ja

**Comment by pstein** [comment]
Thank you for the suggestion.

This does NOT help.
But it has somehow an impact.

When I disable the mentioned statement in userContent.css then the font-size of header does not change but the remaining font attributes.

Or with other words: When I change my good old userContent.css

from
--------------------
* { font-size: 12px !important; line-height: 14px !important; font-weight: normal !important; font-family: Verdana !important;}
--------------------
to
--------------------
* { font-size: 7px !important; line-height: 30px !important; font-weight: 900 !important; font-family: Courier !important;}
--------------------

Then the .....
font-size is applied to message body, only
line-height is applied to header and message-body
font-weight is applied to header only
font-family in applied to message body only
....in Printing Tools NG pdf output

Very strange

Disabling the global font in my userChrome.css has no effect.
If it helps I added my userChrome.css code below.

So the problem is still unsolved.

Some ideas:
I guess the font-size in Printing Tools NG is applied/added to existing CSS ruleset from UserChrome/userContent.css.
Is it applied with "!important" parameter to give priority?

Can I somehow omit the font-specification PTNG "Header" tab and apply a new font specification to Printing Tools NG header part DIRECTLY in userChrome.css?

Therefore I need not only a global font declaration for all UI text but for the header part only.
What are the CSS keys names for that?


------------------ userChrome.css -----------
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

/* to remove Move to .... again sub menu */
#mailContext-moveToFolderAgain {
   display: none !important;
}

/* Global UI font */

* { font-size: 12px !important;
    line-height: 14px !important;
    font-family: Verdana !important;
}

/* */
#threadTree treechildren::-moz-tree-row,
#folderTree treechildren::-moz-tree-row,
#abResultsTree treechildren::-moz-tree-row,
#dirTree treechildren::-moz-tree-row {
   height: 14px !important;
   line-height: 14px !important;
   min-height: 0 !important;
   font-size: 12px !important;
   font-family: Verdana !important;
}

/* when folder has unread messages */
treechildren::-moz-tree-cell-text(hasUnreadMessages-true) {
   color: #3300FF !important;
}

/* when subfolder has unread messages */
treechildren::-moz-tree-cell-text(closed,
subfoldersHaveUnreadMessages-true) {
   color: #0086FF !important;
}

/* when new messages are in folder */
treechildren::-moz-tree-cell-text {
   font-size: 12px !important;
   margin: -3px 0 0 !important;
}

treechildren::-moz-tree-cell-text(unread) {
   font-weight: bold !important;
}



treechildren::-moz-tree-image(folderNameCol) {
      list-style-image: url("folder.svg") !important;
      width: 28px !important;    /* no use; can be deleted */
      height: 28px !important;   /* no use; can be deelted */
}


#folderTree > treechildren::-moz-tree-image {
   width: 12px !important;
   height: 11px !important;
}

#folderTree > treechildren::-moz-tree-cell-text {
   padding-top: 0px !important;
   padding-bottom: 0px !important;
}


#expandedHeaderView {
   background-color: gainsboro !important;
   font-size: 12px !important;
}

/* replace light blue by light grey background color */
#abContactsPanel #results_box,
#folderTree,
#dirTree,
#composeContentBox {
   background-color: #F0F0F0 !important;
}
-----------------------------

**Comment by kiki-ja** [comment]
@pstein

What I have found to be the cause of the problem is that in userContent.css I have specified and described something related to fonts.
This indicates a possible conflict with "PrintingTools NG".

So, try disabling or deleting userContent.css, userChrome.css, and userChrome.js.
Or delete the chrome folder from your Thunderbird profile or move it to a different location.
This will clarify things.

This issue I posted is about an issue with "PrintingTools NG" where the header font cannot be changed.
This is a separate issue from the customization in userContent.css, userChrome.css, and userChrome.js.
Please distinguish the issues properly.

If you wish to be compatible with them, please make another issue.
Sorry, I am close this issue as the cause has been found and resolved.

@kiki-ja

**Comment by cleidigh** [comment]
@pstein 
Did you ever completely remove userchrome css and usercontent.
I am skeptical of just removing one rule.
The global rule like @kiki-ja are really not safe 
@cleidigh

**Comment by pstein** [comment]
Hello Christopher,

of cause I tried this in the past - without success.

But after your recent email I tried it again.
I exit TB, moved userChrome.css, userChrome.js and userContent.css to another folder somewhere outside of TB  Portable.
None of the three configuration files do exist now or are accessible for TB
Then I restarted TB.
The PTNG parameters are as shown in the attached snaphot

Now I varied the Font parameters in PTNG "Headers" Tab and printed your email as sample into PDF (see attached pdfs)

Each pdf has the Font and font size as prefix in filename.

As you can see its almost the same regardless of which font I used - except (!) in one (!) trial with Times New Roman 50.

If I later tried it again with Times New Roman 50 the same result as the other fonts was created.

This is crazy.

Maybe PTNG or TB stores some font in its cache.

Or TB has a lower font size threshold.

Or TB allow only certain fonts

Or PTNG font declaration does not become active because it lacks of the CSS "!important" suffix.

Or PTNG font declaration is overwritten after print start with some TB defaults

or. the PTNG final output is not correctly converted into PDF

or......

BTW: Do I have to exit + restart whole TB after changing PTNG parameters?

**Comment by kiki-ja** [comment]
@pstein

Deleting userChrome.css, userContent.css and ,userChrome.js did not solve the problem, so that is not the cause.

Next, Please check to see if the problem reproduces on any printer.

If the above does not solve the problem, I recommend troubleshooting to try to isolate the problem.
The following methods are available for troubleshooting.
Try them in order and see if they improve.
(Without userChrome.css, userContent.css and ,userChrome.js)

1. Disable all add-ons except PrintingTools NG in the Add-ons Manager.
    In other words, check for add-on conflicts.

2. Clear and initialize all configuration values for PrintingTools NG.
    This is the method of deleting all 'extensions.printingtoolsng.*' in the Config Editor.
    (Thunderbird Setting -> General -> Config Editor)
   Restart Thunderbird.

      Config Editor | Thunderbird Help
      https://support.mozilla.org/en-US/kb/config-editor

3. Create a new Thunderbird profile and install only PrintingTools NG.
    This is an effective way to check for profile corruption.

If the above troubleshooting does not improve the problem, the cause is unknown.

@kiki-ja

**Comment by cleidigh** [comment]
@pstein 
In addition to the debugging suggestions from @kiki-ja I would also check what fonts are used with the user css all removed AND PTNG disabled.
Ultimately the dev tools debugging could identify the style source,however, that would require you to do it.
@cleidigh

**Comment by pstein** [comment]
I have got it (partially):

The solution consists of 3 parts:

1.) First of all in Thunderbird Settings it must be allowed that message can change their font and the minimum font size.
Have a look at the attached snapshot
Here I denied (in the past) to change the font and set a minimum size of 14

2.) Printing Tools NG WebExtension confused the user that it CAN change the header font although cannot.
PTNG should check whether a font and font size change is possible at all.
If it it not (like here) then the header font change drop down should be disabled/greyed out and "set by Thunderbird" or similar should be shown.

3.) Then at last my userChrome.css or UserContent.css comes into play.
After PTNG changed the font userChrome.css or userContent.css modifies (again) the current header font
So it has the highest priority.

I have to investigate which of the multiple CSS statements refers to the message header font.
Do you have an idea?
I am not an userChrome.css expert.

I wrote this in official github thread too
