### ISSUE TITLE
Show "Print NG" Toolbar button not only in preview pane but in mesage pane too

### ISSUE THREAD

**Issue by pstein** [cleidigh/printing-tools-ng#211]
When I mark a certain message line in message list pane then the content is shown in the message preview pane below.
And in the message preview panes toolbar the button "Print NG" appears. Good.

Now when I double click on the same message in the message list an own message window opens with the corresponding message.

But no "Print NG" button is visible in the window toolbar.

How can I enable it?

**Comment by Jayonas** [comment]
Normally you would do this by right-clicking on the window's toolbar and choosing "Customize", then dragging the Print NG button out of the list of available buttons onto the toolbar at whatever location you want.

However, as someone who has had the Print NG button on their message window toolbar for at least a year -- after the latest update the button has disappeared from my message window toolbar, and is no longer in the list of available buttons for message windows.  It still exists for the main window, but not for message windows.

I'm pretty sure that people who use message windows (instead of tabs or the preview pane) are a small minority of Thunderbird users, so plugin authors easily forget to add their buttons to message windows, and they also easily forget to test their plugins in message windows.  Hopefully it's a quick and easy fix to re-enable the Print NG button for message windows.

**Comment by cleidigh** [comment]
@pstein 
This is actually something I continue to investigate as something may have been deprecated in the old world and getting it with the webext APIS is not in place yet . I will see what I can learn in our dev call this week.
@cleidigh

**Comment by cleidigh** [comment]
@Jayonas 
@pstein 
Nope... Mea-culpa.
@Jayonas was essentially right. An error without being caught in testing.
I will do a patch.
@cleidigh

**Comment by cleidigh** [comment]
@pstein 
Here is a beta fix for the button issue : 
https://github.com/cleidigh/printing-tools-ng/blob/v2.2.3/xpi/Beta/printing-tools-ng-2.2.3-b1-tb.xpi
@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
Christopher, recogniized that issue recently too.
Works now after install of 2.2.3-b1. Perfect

**Comment by Jayonas** [comment]
Confirmed that the beta resolves the problem for me.  The Print NG button automatically resumed its place in my message window toolbar when I updated. :)  I totally understand missing a regression that's off the beaten path (especially in an app like Thunderbird with so many dark and forgotten paths), definitely done that myself.  Thanks much for the quick investigation and fix, it's greatly appreciated!

**Comment by cleidigh** [comment]
@Jayonas 
@tidebre67 
 Thanks for the confirmation.
@Jayonas Appreciate the acknowledgement that all is not simple, especially with the upcoming 115 changes. The reality is that PTNG requires a lot of under the hood tricks to as cleanly as possible hook into /take over the prnt and preview functions. Having users like yourself and @tidebre67 involved and enthusiastic is why I do this work!
Thanks both.
@cleidigh

**Comment by Jayonas** [comment]
@cleidigh

You're very welcome, I'm happy to give credit where it's due. :)  Sorry if my initial comment in this thread sounded harsh, that was definitely not my intention.  I've just run into several plugins that apparently haven't even thought to support separate message windows, and since they're not used by default I figure that's just too far off the beaten path for a lot of authors.  Maybe they would add it if I asked, but at some point it's more effort than it's worth for me to figure out the best way to contact each project and then do so because it also seems just as likely that the project will turn out to be effectively dead or my email will go unanswered.  It's just a peril of open source projects whose functionality to developer ratio has gotten too high.

Anyway, although I've never looked at Thunderbird's internals, I can easily imagine the sorts of tricks that you need to play to integrate so well with the built-in printing functionality, and that kind of thing is always very prone to difficulty and error, so thanks again for diving into difficult areas and working to improve the lives of so many users!  This plugin has been really helpful to me in general, and the new auto-saving PDF feature has been especially great.

Cheers!

**Comment by pstein** [comment]
When will be v2.2.3 be delivered as final?

**Comment by cleidigh** [comment]
@pstein 
I have been heads down with updates for 115.
I will try to peel away soon and release...
@cleidigh

**Comment by cleidigh** [comment]
@pstein 
@Jayonas 
v2.2.3 is released.
Thanks for your patience!
@cleidigh
