### ISSUE TITLE
Headers Order not working Thunderbird 78.8.0

### ISSUE THREAD

**Issue by cloverdavid** [cleidigh/printing-tools-ng#27]
A fairly new user of this add-on. Printing Tools NG is a wonderful add-on. It worked well until the latest T'bird update, 78.8.0. When I set the order of the Headers, this is not the order that shows up when I open an email, and the date received does not show. HOWEVER, when I select **Print Preview** the headers are all in the correct order and will print correctly. Hope this can be fixed. 

I have supported a number of unique and helpful add-ons, and plan to support yours as soon as I see it working completely.
Many thanks!
David

**Comment by cleidigh** [comment]
@cloverdavid 
thanks for the post.  I think you might have an interpretation on the extensions intent.
While I am not  the original author , I have made several enhancements since taking over
the extension  which was abandoned.  One of the more recent was adding the ability
to change the order or show and hide common and some extended headers.
The extension does not and never has manipulated Thunderbirds message view the extension only intercepts print/Preview to allow the various layout and header content.

manipulating the native message view would be another whole level of complexity.  I am not even sure there would be a consistent/future possibility to do this even if it would be convenient and I don't think this should be considered a bug as the extension is doing what it is advertised to do.  I am bit confused because you imply something was different before.  have I misinterpreted anything ?

just as a note, the date received is one example of an extended header which is not shown in message view.
cheers
Christopher

**Comment by cloverdavid** [comment]
Christopher,
    Thanks for your email.
          Your explanation makes perfect sense to me. To tell you the
          truth, I never paid a lot of attention to the order of the
          headers when messages appeared in my inbox and I'm not sure
          whether the order I selected was being followed. Probably not.
          I found that when I have the cursor on an incoming message and
          press Alt-F, then v, the message is opened in the print
          preview mode where I can see all of the headers in the right
          order.
    Again, thank you for an
          excellent Thunderbird add-on. I've made a donation to the
          cause.
        
    David
    
    On 2/24/2021 7:58 PM, Christopher
      Leidigh wrote:
    
    
      
      @cloverdavid
        thanks for the post. I think you might have an interpretation on
        the extensions intent.
        While I am not the original author , I have made several
        enhancements since taking over
        the extension which was abandoned. One of the more recent was
        adding the ability
        to change the order or show and hide common and some extended
        headers.
        The extension does not and never has manipulated Thunderbirds
        message view the extension only intercepts print/Preview to
        allow the various layout and header content.
      manipulating the native message view would be another whole
        level of complexity. I am not even sure there would be a
        consistent/future possibility to do this even if it would be
        convenient and I don't think this should be considered a bug as
        the extension is doing what it is advertised to do. I am bit
        confused because you imply something was different before. have
        I misinterpreted anything ?
      just as a note, the date received is one example of an extended
        header which is not shown in message view.
        cheers
        Christopher
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cleidigh/printing-tools-ng/issues/27#issuecomment-785558890",
"url": "https://github.com/cleidigh/printing-tools-ng/issues/27#issuecomment-785558890",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by cleidigh** [comment]
@cloverdavid 
great! 
thank you very much for the donation!
glad the extension is useful for you.
cheers
Christopher
