### ISSUE TITLE
Printing a selected text works only, when previewing the print before

### ISSUE THREAD

**Issue by loveouzo** [cleidigh/printing-tools-ng#8]
Hi!

I am very happy that there is a new version of printing tools for TB. Thank you for this!

I installed your addon today, checked the "Print selected text" box and tried to print a selected passage from an e-mail.
When I use the print preview and click "Print" in the print preview window, it will print as desired. When I just press Ctrl+P or use the menu "File" -> "Print" or use the "Print"-Button in the main toolbar, the whole e-mail ist printed although the passage is still selected.

I use TB 68.10.0 (Win 32-Bit).

Thank you!:)

**Comment by cleidigh** [comment]
@loveouzo 
Ha! I love your user ID, I personally do not like ouzo despite being married to a Greek ;-)
thanks for the post and kudos.
I will have to check this, there are different paths to the printing and I am wondering if the "direct" ControlP bypasses the printing override.
@cleidigh

**Comment by madvinegar** [comment]
I tried v2.0.5 beta7 but unfortunately the "print selection" does not work unless I firstly open the email in print preview.

**Comment by cleidigh** [comment]
@madvinegar 
indeed, married to a true Cretan!
I will do some testing using Greek
yassou!
Christopher

**Comment by madvinegar** [comment]
Thank you very much Chris! Cretans are known to be strong and fearless, but I suppose you already know this by now. :)

Please do some testing with the Greek Language. This might be the culprit.

Also, one last question. Is there any chance you can make the printing tools work with the beta versions of thunderbird?
The reason I am asking is because I also have an M1 Macbook pro, and only the beta versions (87 and 88) work natively with apple silicon. So I cannot install printing tools in my M1 MBP.

**Comment by cleidigh** [comment]
@loveouzo 
finally got This
check out b9  in #61 
Christopher

**Comment by cleidigh** [comment]
Closed w/v2.0.5

**Comment by loveouzo** [comment]
Hi Christopher, thank you very much!

**Comment by madvinegar** [comment]
Just to confirm the problem is fixed. Found the culprit. The mistake I was making when transferring my old inbox and old sent files was that I was also transferring the inbox.msf and sent.msf files.
The trick is to transfer just the inbox and sent files and let the system re-build the msf files.
@kiki-ja correctly pointed this out.

So now I can print selection without any problem.
Thank you all for your assistance!
@cleidigh
